### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by ljy1998-cool** [blhprasanna99/speech_emotion_detection#1]
i want to know how to make all wavs into spectrogram

**Comment by blhprasanna99** [comment]
we have used spek tool in order to convert those into spectograms (manually).....

**Comment by ljy1998-cool** [comment]
can you sent me the spectrograms database please?my email is 13161656188@163.com
thank you !!!!!

**Comment by blhprasanna99** [comment]
it's a huge data set gmail doesn't allow that much data to be sent

**Comment by blhprasanna99** [comment]
RESOLVED

**Comment by canibal1** [comment]
Hey. Can you send me spectrograms database please? furkangny21@gmail.com
Thank you :)
